@startuml

package Personnage{

    Class Personnage{
        -nom : String
        -classe : Classe
        -inventaire : Equipment[*]
        -armor : Armor
        -weapons : Weapon

        -speed:Integer
        -strenght:Integer
        -dex:Integer
        +initiative:Integer

        +<<create>> Personnages(nom:String,race:Races,classe:Classes,caractéristiques:Caractéristiques,inventaire:Equipment.Equipment[*],équipé:Equipment.Equipment[2])
    }


    Personnage "-classe"*-> Classe : "est de classe : "
    Personnage "-caractéristique"*->Caractéristique : ""

    Class Caractéristique{

    }

    Class Classe{

    }

}


package Equipment {
    Class Equipment{
        -name: String
        +getName() : String
    }

    package Armor {
        Abstract Armor Extends Equipment.Equipment{
            -class : Integer
            -speed_modifier : Integer
            + getClass() : Integer
            + getSpeedModifier() : Integer
        }

        Abstract Heavy implements Armor {

        }

        Abstract Light implements Armor {

        }


    }

    package Weapon {
        Abstract Weapon Extends Equipment.Equipment {
            -damage : Dice
            -range : Integer

            +getDamage() : Dice
            +getRange() : Integer
        }

        Abstract Simple implements Weapon {

        }

        Abstract Martial implements Weapon {

        }

        Abstract Ranged implements Weapon {

        }
    }

}
Personnage "-inventaire"*->Equipment.Equipment: ""

package Race{
    abstract class Race{
        -baseSpeed:Integer
        -baseDex:Integer
        -baseStrenght:Integer
        -baseInitiative:Integer

        +getBaseSpeed():Integer
        +getBaseStrenght():Integer
        +getBaseDex():Integer
        +getBaseInitiative():Integer

    }

    Class Human extends Race{
        +<<create>>Human()
    }
    Class Dwarf extends Race{
        +<<create>>Dwarf()
    }
    Class Elf extends Race{
        +<<create>>Elf()
    }
    Class Halfelin extends Race{
        +<<create>>Halfelin()
    }


}
Personnage "-race"*->Race.Race : "est de race >"


@enduml