@startuml

package Entity {
    Abstract Entity {
        -posX:Integer
        -posY:Integer
        -hp:Integer
        -strength:Integer
        -dex:Integer
        -initiative:Integer
        -speed:Integer

        +getPosX():Integer
        +getPosY():Integer
        +getHp():Integer
        +getStrength():Integer
        +getDex():Integer
        +getInitiative():Integer
        +getSpeed():Integer
    }

    package Monstre {
        class Monstre extends Entity.Entity {
            -species:String
            -id:Integer
            -atkRange:Integer
            -armorClass:Integer
        }
    }

    package Personnage{

        Class Personnage extends Entity.Entity {
            -name : String
            +<<create>> Personnage(nom:String,race:Races,class:Class)

        }

        package Class{
            abstract Class Class{
                -basHealth:Integer
                +<<create>>Class()
                +getHealth():Integer
            }

            Class Clerc extends Class{
                +<<create>>Clerc()
            }
            Class Warrior extends Class{
                +<<create>>Warrior()
            }
            Class Wizard extends Class{
               +<<create>>Wizard()
            }
        }

        package Race{
            abstract class Race{
                -baseSpeed:Integer
                -baseDex:Integer
                -baseStrength:Integer
                -baseInitiative:Integer

                +getBaseSpeed():Integer
                +getBaseStrength():Integer
                +getBaseDex():Integer
                +getBaseInitiative():Integer

            }

            Class Human extends Race{
                +<<create>>Human()
            }
            Class Dwarf extends Race{
                +<<create>>Dwarf()
            }
            Class Elf extends Race{
                +<<create>>Elf()
            }
            Class Halfelin extends Race{
                +<<create>>Halfelin()
            }
        }

    }
}

package Equipment {
    Class Equipment{
        -name: String
        +getName() : String
    }

    package Armor {
        Abstract Armor Extends Equipment.Equipment{
            -class : Integer
            -speedModifier : Integer
            + getClass() : Integer
            + getSpeedModifier() : Integer
        }

        Abstract Heavy Extends Armor {

        }

        Abstract Light Extends Armor {

        }

        Class ScaleMail Extends Light {

        }

        Class HalfPlate Extends Light {

        }

        Class ChainMail Extends Heavy {

        }

        Class Plate Extends Heavy {

        }
    }

    package Weapon {
        Abstract Weapon Extends Equipment.Equipment {
            -range : Integer

            +getRange() : Integer
        }

        Abstract Simple extends Weapon {

        }

        Abstract Martial extends Weapon {

        }

        Abstract Ranged extends Weapon {

        }

        class Quarterstaff extends Simple {

        }

        class Mace extends Simple {

        }

        class Longsword extends Martial {

        }

        class Rapier extends Martial {

        }

        class Crossbow extends Ranged {

        }

        class Sling extends Ranged {

        }

        class Shortbow extends Ranged {

        }
    }

}

package Dice{
    Class Dice{
        -value:Integer
        -nbTrhow:Integer
        +<<create>>Dice(trhow:Integer,value:Integer)
        +trhrow():Integer
    }
}

package Donjon{
    Class Donjon{
        +<<create>>Donjon()
        +displayDonjon()
    }
}


Entity.Personnage.Personnage "-class"*-> Entity.Personnage.Class.Class : "Est de classe : "
Entity.Personnage.Personnage "-inventory"*-> Equipment.Equipment : "A les équipements : "
Entity.Personnage.Personnage "-weapon"*-> Equipment.Weapon.Weapon : "Armé équipes : "
Entity.Personnage.Personnage "-armor"*-> Equipment.Armor.Armor : "Possède l'armure : "
Entity.Personnage.Personnage "-race"*->Entity.Personnage.Race.Race : "est de race >"
Entity.Personnage.Personnage "+getClass()"*-> Entity.Personnage.Class.Class : "Getter Est de classe : "
Entity.Personnage.Personnage "+getInventory()"*-> Equipment.Equipment : "Getter A les équipements : "
Entity.Personnage.Personnage "+getWeapon()"*-> Equipment.Weapon.Weapon : "Getter Armé équipes : "
Entity.Personnage.Personnage "+getArmor()"*-> Equipment.Armor.Armor : "Getter Possède l'armure : "
Entity.Personnage.Personnage "+getRace()"*->Entity.Personnage.Race.Race : "Getter est de race >"

Entity.Personnage.Personnage "+equip(weapon:Weapon)"*-> Equipment.Weapon.Weapon : "Équipe une arme : "
Entity.Personnage.Personnage "+take(equipment:Equipment)"*-> Equipment.Equipment : "Récupère un équipement : "

Entity.Personnage.Class.Class "+getBaseStuff()" *--> Equipment.Equipment:"getter à pour stuff de base >"
Entity.Personnage.Class.Class "-baseStuff[*]" *--> Equipment.Equipment:"à pour stuff de base >"

Equipment.Weapon.Weapon "-damage"*-> Dice.Dice : "Dés de dommages"
Equipment.Weapon.Weapon "getDamage()"*-> Dice.Dice : "Getter dés de dommages"

Entity.Monstre.Monstre "-atkDamage"*->Dice.Dice : "Dés de dommages"
Entity.Monstre.Monstre "+getAtkDamage()"*->Dice.Dice : "Getter Dés de dommages"

@enduml