@startuml

package Personnage{

    Class Personnage{
        -name : String
        -class : Classe
        -inventory : Equipment[*]
        -armor : Armor
        -weapons : Weapon[*]

        -speed:Integer
        -strength:Integer
        -dex:Integer
        -initiative:Integer

        +<<create>> Personnage(nom:String,race:Races,classe:Classes)
    }

}
Personnage.Personnage "-classe"*-> Classes.Classe : "est de classe : "
package Classes{
    abstract Class Classe{
        -basHealth:Integer
        +<<create>>Classe()
        +getHealth():Integer
        +getBaseStuff():Equipment.Equipment
    }

    Class Clerc extends Classe{
        +<<create>>Clerc()
    }
    Class Warrior extends Classe{
        +<<create>>Warrior()
    }
    Class Wizard extends Classe{
       +<<create>>Wizard()
    }
}

Classe "-baseStuff[*]" *--> Equipment.Equipment:"à pour stuff de base >"

package Equipment {
    Class Equipment{
        -name: String
        +getName() : String
    }

    package Armor {
        Abstract Armor Extends Equipment.Equipment{
            -class : Integer
            -speedModifier : Integer
            + getClass() : Integer
            + getSpeedModifier() : Integer
        }

        Abstract Heavy Extends Armor {

        }

        Abstract Light Extends Armor {

        }

        Class ScaleMail Extends Light {

        }

        Class HalfPlate Extends Light {

        }

        Class ChainMail Extends Heavy {

        }

        Class Plate Extends Heavy {

        }
    }

    package Weapon {
        Abstract Weapon Extends Equipment.Equipment {
            -damage : Dice.Dice
            -range : Integer

            +getDamage() : Dice.Dice
            +getRange() : Integer
        }

        Abstract Simple extends Weapon {

        }

        Abstract Martial extends Weapon {

        }

        Abstract Ranged extends Weapon {

        }

        class Quarterstaff extends Simple {

        }

        class Mace extends Simple {

        }

        class Longsword extends Martial {

        }

        class Rapier extends Martial {

        }

        class Crossbow extends Ranged {

        }

        class Sling extends Ranged {

        }

        class Shortbow extends Ranged {

        }
    }
}

Personnage.Personnage "-inventaire"*->Equipment.Equipment: ""

package Race{
    abstract class Race{
        -baseSpeed:Integer
        -baseDex:Integer
        -baseStrength:Integer
        -baseInitiative:Integer

        +getBaseSpeed():Integer
        +getBaseStrength():Integer
        +getBaseDex():Integer
        +getBaseInitiative():Integer

    }

    Class Human extends Race{
        +<<create>>Human()
    }
    Class Dwarf extends Race{
        +<<create>>Dwarf()
    }
    Class Elf extends Race{
        +<<create>>Elf()
    }
    Class Halfelin extends Race{
        +<<create>>Halfelin()
    }


}
Personnage.Personnage "-race"*->Race.Race : "est de race >"

package Monstre {
    class Monstre {
        -species:String
        -id:Integer

        -atkRange:Integer


        -hp:Integer
        -strength:Integer
        -dex:Integer
        -armorClass:Integer
        -initiative:Integer
    }
}
Monstre.Monstre "-atkDamage"*->Dice.Dice : "Dés de dommages"

package Dice{
    Class Dice{
        -value:Integer
        -nbTrhow:Integer
        +<<create>>Dice(trhow:Integer,value:Integer)
        +trhrow():Integer
    }
}

@enduml